[api_keys]
SOLCAST_API_KEY= "k9EpTzWzwZuUEBZYhz4Q4LSnFpYDU8_J"
GEMINI_API_KEY= "AIzaSyD2t_a3rDYbGZGpTVowRIKrgR0qt4N8miI"
IMGDB_API_KEY= "e9a6a3636c80aca442e2630206bbd5a5"
DINO_TOKEN= "cea5f0e3597cd0bb56548d77a3060683"
